import type { Appointment } from "../domain/appointments";
import type { AuditEvent } from "../domain/audit";
import type {
  AutomationDefinition,
  AutomationRun,
  CarePathway,
  CarePathwayEnrollment,
} from "../domain/automations";
import type { AudienceSnapshot, Campaign } from "../domain/campaigns";
import type { ConsentRecord, Contact, ContactSuppressionState } from "../domain/contacts";
import type { Conversation, Message } from "../domain/conversations";
import type { LabReportMetadata } from "../domain/laboratory";
import {
  correlationId,
  encryptedValueRef,
  externalReference,
  isoDate,
  isoDateTime,
  requestId,
  sha256Digest,
  timeZone,
} from "../domain/primitives";
import type { MessageTemplate, MessageTemplateVersion } from "../domain/templates";
import type { DailyMetric, UsageLedgerEntry } from "../domain/usage";
import {
  EXTERNAL_MESSAGING_DISABLED,
  type Location,
  type Team,
  type StaffIdentity,
  type WhatsAppConnection,
  type Workspace,
  type WorkspaceMembership,
} from "../domain/workspaces";
import {
  SYNTHETIC_CAMPAIGN_SIZE,
  summarizeSyntheticAudience,
  syntheticAudienceMember,
} from "./campaign-audience";
import { DEMO_IDS } from "./ids";

export const DEMO_CLOCK = {
  now: isoDateTime("2026-08-07T12:30:00.000Z"),
  created: isoDateTime("2026-08-01T03:30:00.000Z"),
  earlier: isoDateTime("2026-08-07T10:15:00.000Z"),
  recent: isoDateTime("2026-08-07T12:20:00.000Z"),
  serviceWindowExpiry: isoDateTime("2026-08-08T10:15:00.000Z"),
} as const;

const colombo = timeZone("Asia/Colombo");

export const demoWorkspaces: readonly Workspace[] = [
  {
    id: DEMO_IDS.workspaces.safeNet,
    name: "SafeNet Healthcare Platform Demo",
    mode: "demo",
    status: "active",
    timeZone: colombo,
    supportedLanguages: ["en", "si", "ta"],
    defaultLanguage: "en",
    retentionPolicyVersion: "demo-retention-v1",
    dataClassification: "synthetic_only",
    externalMessaging: EXTERNAL_MESSAGING_DISABLED,
    isSyntheticDemo: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.workspaces.hemasLocked,
    name: "Hemas onboarding — locked and not connected",
    mode: "production",
    status: "locked",
    timeZone: colombo,
    supportedLanguages: ["en", "si", "ta"],
    defaultLanguage: "en",
    retentionPolicyVersion: "pending-hemas-approval",
    dataClassification: "regulated_patient_data",
    externalMessaging: {
      ...EXTERNAL_MESSAGING_DISABLED,
      disabledReason: "Locked until Hemas-owned Firebase, Meta and governance gates are completed.",
    },
    isSyntheticDemo: false,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

const staffIdentityBlueprints: readonly (readonly [StaffIdentity["uid"], string, string])[] = [
  [DEMO_IDS.users.admin, "Demo tenant administrator", "a•••@demo.invalid"],
  [DEMO_IDS.users.supervisor, "Demo patient services supervisor", "s•••@demo.invalid"],
  [DEMO_IDS.users.agent, "Demo front-desk agent", "f•••@demo.invalid"],
  [DEMO_IDS.users.campaignOperator, "Demo campaign operator", "o•••@demo.invalid"],
  [DEMO_IDS.users.campaignApprover, "Demo campaign approver", "c•••@demo.invalid"],
  [DEMO_IDS.users.privacyReviewer, "Demo privacy reviewer", "p•••@demo.invalid"],
  [DEMO_IDS.users.clinicalApprover, "Synthetic clinical approver", "g•••@demo.invalid"],
];

export const demoStaffIdentities: readonly StaffIdentity[] = staffIdentityBlueprints.map(
  ([uid, displayLabel, maskedEmail]): StaffIdentity => ({
  uid,
  displayLabel,
  maskedEmail,
  identityProvider: "demo",
  status: "active",
  synthetic: true,
  createdAt: DEMO_CLOCK.created,
  updatedAt: DEMO_CLOCK.recent,
  }),
);

export const demoLocations: readonly Location[] = [
  {
    id: DEMO_IDS.locations.wattala,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Demo Hospital — Wattala",
    kind: "hospital",
    city: "Wattala",
    supportedServiceRefs: ["demo-general-medicine", "demo-channeling", "demo-laboratory"],
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.locations.thalawathugoda,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Demo Hospital — Thalawathugoda",
    kind: "hospital",
    city: "Thalawathugoda",
    supportedServiceRefs: ["demo-general-medicine", "demo-channeling", "demo-packages"],
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.locations.labNetwork,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Synthetic nationwide laboratory network",
    kind: "laboratory",
    city: "Sri Lanka",
    supportedServiceRefs: ["demo-centre-visit", "demo-home-collection"],
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoTeams: readonly Team[] = [
  {
    id: DEMO_IDS.teams.general,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "General patient services",
    queueType: "general",
    locationIds: [DEMO_IDS.locations.wattala, DEMO_IDS.locations.thalawathugoda],
    businessHoursLabel: "Synthetic schedule: 08:00–20:00 Asia/Colombo",
    firstResponseSlaMinutes: 5,
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.teams.laboratory,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Laboratory services",
    queueType: "laboratory",
    locationIds: [DEMO_IDS.locations.labNetwork],
    businessHoursLabel: "Synthetic schedule: 07:00–19:00 Asia/Colombo",
    firstResponseSlaMinutes: 5,
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.teams.clinicalEscalation,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Clinical safety escalation — simulator",
    queueType: "clinical_escalation",
    locationIds: [DEMO_IDS.locations.wattala, DEMO_IDS.locations.thalawathugoda],
    businessHoursLabel: "Synthetic on-call path",
    firstResponseSlaMinutes: 2,
    active: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoMemberships: readonly WorkspaceMembership[] = [
  {
    id: DEMO_IDS.members.admin,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.admin,
    displayLabel: "Demo tenant administrator",
    role: "tenant_admin",
    scopeMode: "workspace_wide",
    teamIds: [],
    locationIds: [],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.supervisor,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.supervisor,
    displayLabel: "Demo patient services supervisor",
    role: "supervisor",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.general, DEMO_IDS.teams.laboratory],
    locationIds: [
      DEMO_IDS.locations.wattala,
      DEMO_IDS.locations.thalawathugoda,
      DEMO_IDS.locations.labNetwork,
    ],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.agent,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.agent,
    displayLabel: "Demo front-desk agent",
    role: "agent",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.general],
    locationIds: [DEMO_IDS.locations.wattala],
    status: "active",
    mfaSatisfied: false,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.campaignOperator,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.campaignOperator,
    displayLabel: "Demo campaign operator",
    role: "campaign_operator",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.general],
    locationIds: [DEMO_IDS.locations.wattala, DEMO_IDS.locations.thalawathugoda],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.campaignApprover,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.campaignApprover,
    displayLabel: "Demo campaign approver",
    role: "campaign_approver",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.general],
    locationIds: [DEMO_IDS.locations.wattala, DEMO_IDS.locations.thalawathugoda],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.privacyReviewer,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.privacyReviewer,
    displayLabel: "Demo privacy reviewer",
    role: "privacy_reviewer",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.general, DEMO_IDS.teams.laboratory],
    locationIds: [
      DEMO_IDS.locations.wattala,
      DEMO_IDS.locations.thalawathugoda,
      DEMO_IDS.locations.labNetwork,
    ],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.members.clinicalApprover,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    uid: DEMO_IDS.users.clinicalApprover,
    displayLabel: "Synthetic clinical approver",
    role: "clinical_approver",
    scopeMode: "assigned",
    teamIds: [DEMO_IDS.teams.clinicalEscalation],
    locationIds: [DEMO_IDS.locations.wattala, DEMO_IDS.locations.thalawathugoda],
    status: "active",
    mfaSatisfied: true,
    lastAuthenticatedAt: DEMO_CLOCK.recent,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoConnections: readonly WhatsAppConnection[] = [
  {
    id: DEMO_IDS.connections.simulator,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    displayName: "Local WhatsApp journey simulator",
    provider: "simulator",
    status: "mock",
    maskedNumber: "No external number",
    providerPhoneNumberId: null,
    wabaId: null,
    credentialSecretRef: null,
    qualityRating: "unknown",
    messagingLimit: null,
    verification: {
      source: "simulator",
      status: "verified",
      checkedAt: DEMO_CLOCK.recent,
      detail: "Internal deterministic simulator only; this is not a Meta connection.",
    },
    externalMessagingEnabled: false,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.connections.hemasLocked,
    workspaceId: DEMO_IDS.workspaces.hemasLocked,
    displayName: "Hemas-owned Meta connection — setup pending",
    provider: "meta_cloud_api",
    status: "not_configured",
    maskedNumber: "Not configured",
    providerPhoneNumberId: null,
    wabaId: null,
    credentialSecretRef: null,
    qualityRating: "unknown",
    messagingLimit: null,
    verification: {
      source: "manual",
      status: "unverified",
      checkedAt: null,
      detail: "Requires Hemas ownership and controlled end-to-end verification.",
    },
    externalMessagingEnabled: false,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

function suppression(overrides: Partial<ContactSuppressionState> = {}): ContactSuppressionState {
  return {
    suppressAll: false,
    suppressMarketing: false,
    invalidContact: false,
    reasons: [],
    updatedAt: DEMO_CLOCK.recent,
    ...overrides,
  };
}

const contactBlueprints = [
  [DEMO_IDS.contacts.appointment, "Synthetic Patient A", "en", ["appointment"]],
  [DEMO_IDS.contacts.laboratory, "Synthetic Patient B", "si", ["laboratory"]],
  [DEMO_IDS.contacts.package, "Synthetic Patient C", "ta", ["package"]],
  [DEMO_IDS.contacts.mixedLanguage, "Synthetic Patient D", "en", ["human-handoff"]],
  [DEMO_IDS.contacts.urgent, "Synthetic Patient E", "en", ["urgent-simulation"]],
  [DEMO_IDS.contacts.stopped, "Synthetic Patient F", "en", ["marketing-suppressed"]],
] as const;

export const demoContacts: readonly Contact[] = contactBlueprints.map(
  ([id, displayLabel, preferredLanguage, tags], index): Contact => ({
    id,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    phoneLookupHmac: syntheticAudienceMember(index).deterministicHmacId,
    encryptedPhoneRef: encryptedValueRef(`demo://phone/synthetic-${index + 1}`),
    maskedPhone: `+94 •• ••• ${String(101 + index).padStart(4, "0")}`,
    encryptedDisplayNameRef: encryptedValueRef(`demo://display-name/synthetic-${index + 1}`),
    displayLabel,
    externalPatientRef: externalReference(`DEMO-PAT-${String(index + 1).padStart(4, "0")}`),
    preferredLanguage,
    alternateLanguages: [],
    suppression:
      id === DEMO_IDS.contacts.stopped
        ? suppression({
            suppressMarketing: true,
            reasons: ["stop_keyword"],
          })
        : suppression(),
    tags,
    synthetic: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  }),
);

export const demoConsentRecords: readonly ConsentRecord[] = [
  {
    id: DEMO_IDS.consents.appointment,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.appointment,
    purpose: "appointment_service",
    channel: "whatsapp",
    category: "service",
    status: "granted",
    source: "synthetic_fixture",
    noticeVersion: "demo-notice-v1",
    language: "en",
    evidenceRef: "demo://consent/appointment-a",
    capturedAt: DEMO_CLOCK.earlier,
    withdrawnAt: null,
    supersedesRecordId: null,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.earlier,
  },
  {
    id: DEMO_IDS.consents.laboratory,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.laboratory,
    purpose: "laboratory_service",
    channel: "whatsapp",
    category: "utility",
    status: "granted",
    source: "synthetic_fixture",
    noticeVersion: "demo-notice-v1",
    language: "si",
    evidenceRef: "demo://consent/laboratory-b",
    capturedAt: DEMO_CLOCK.earlier,
    withdrawnAt: null,
    supersedesRecordId: null,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.earlier,
  },
  {
    id: DEMO_IDS.consents.packageMarketing,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.package,
    purpose: "health_campaigns",
    channel: "whatsapp",
    category: "marketing",
    status: "granted",
    source: "synthetic_fixture",
    noticeVersion: "demo-marketing-notice-v1",
    language: "ta",
    evidenceRef: "demo://consent/package-c",
    capturedAt: DEMO_CLOCK.earlier,
    withdrawnAt: null,
    supersedesRecordId: null,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.earlier,
  },
  {
    id: DEMO_IDS.consents.stoppedGranted,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.stopped,
    purpose: "health_campaigns",
    channel: "whatsapp",
    category: "marketing",
    status: "granted",
    source: "synthetic_fixture",
    noticeVersion: "demo-marketing-notice-v1",
    language: "en",
    evidenceRef: "demo://consent/stop-before",
    capturedAt: isoDateTime("2026-08-01T05:00:00.000Z"),
    withdrawnAt: null,
    supersedesRecordId: null,
    createdAt: isoDateTime("2026-08-01T05:00:00.000Z"),
    updatedAt: isoDateTime("2026-08-01T05:00:00.000Z"),
  },
  {
    id: DEMO_IDS.consents.stoppedWithdrawn,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.stopped,
    purpose: "health_campaigns",
    channel: "whatsapp",
    category: "marketing",
    status: "withdrawn",
    source: "inbound_keyword",
    noticeVersion: "demo-marketing-notice-v1",
    language: "en",
    evidenceRef: "demo://consent/stop-keyword-event",
    capturedAt: DEMO_CLOCK.recent,
    withdrawnAt: DEMO_CLOCK.recent,
    supersedesRecordId: DEMO_IDS.consents.stoppedGranted,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.consents.carePathway,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    contactId: DEMO_IDS.contacts.urgent,
    purpose: "care_pathway",
    channel: "whatsapp",
    category: "utility",
    status: "granted",
    source: "synthetic_fixture",
    noticeVersion: "demo-care-notice-v1",
    language: "en",
    evidenceRef: "demo://consent/care-e",
    capturedAt: DEMO_CLOCK.earlier,
    withdrawnAt: null,
    supersedesRecordId: null,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.earlier,
  },
];

const conversationBase = {
  workspaceId: DEMO_IDS.workspaces.safeNet,
  connectionId: DEMO_IDS.connections.simulator,
  status: "active" as const,
  mode: "automation" as const,
  assigneeId: null,
  serviceWindowExpiresAt: DEMO_CLOCK.serviceWindowExpiry,
  firstResponseDueAt: isoDateTime("2026-08-07T12:35:00.000Z"),
  lastMessageAt: DEMO_CLOCK.recent,
  unreadCount: 1,
  synthetic: true,
  createdAt: DEMO_CLOCK.earlier,
  updatedAt: DEMO_CLOCK.recent,
};

export const demoConversations: readonly Conversation[] = [
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.appointment,
    contactId: DEMO_IDS.contacts.appointment,
    teamId: DEMO_IDS.teams.general,
    detectedLanguage: "en",
    languageConfidence: 0.99,
    purpose: "appointment",
    handoffSummary: "Synthetic appointment enquiry; no real patient information.",
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.laboratory,
    contactId: DEMO_IDS.contacts.laboratory,
    teamId: DEMO_IDS.teams.laboratory,
    detectedLanguage: "si",
    languageConfidence: 0.96,
    purpose: "laboratory",
    handoffSummary: "Synthetic Sinhala laboratory-service enquiry.",
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.package,
    contactId: DEMO_IDS.contacts.package,
    teamId: DEMO_IDS.teams.general,
    detectedLanguage: "ta",
    languageConfidence: 0.98,
    purpose: "package",
    handoffSummary: "Synthetic Tamil package enquiry.",
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.mixedLanguage,
    contactId: DEMO_IDS.contacts.mixedLanguage,
    teamId: DEMO_IDS.teams.general,
    status: "assigned",
    mode: "human_takeover",
    assigneeId: DEMO_IDS.members.agent,
    detectedLanguage: "en",
    languageConfidence: 0.42,
    purpose: "general_support",
    handoffSummary: "Low-confidence mixed-language simulation routed to a human.",
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.urgent,
    contactId: DEMO_IDS.contacts.urgent,
    teamId: DEMO_IDS.teams.clinicalEscalation,
    status: "escalated",
    mode: "safety_hold",
    detectedLanguage: "en",
    languageConfidence: 0.99,
    purpose: "urgent_escalation",
    firstResponseDueAt: isoDateTime("2026-08-07T12:22:00.000Z"),
    handoffSummary: "Synthetic urgent-language trigger; routine automation is paused.",
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.phase5Care,
    contactId: DEMO_IDS.contacts.urgent,
    teamId: DEMO_IDS.teams.clinicalEscalation,
    detectedLanguage: "en",
    languageConfidence: 1,
    purpose: "care_pathway",
    handoffSummary:
      "Synthetic Phase 5 care-control route; no patient or clinical content.",
    unreadCount: 0,
  },
  {
    ...conversationBase,
    id: DEMO_IDS.conversations.stopped,
    contactId: DEMO_IDS.contacts.stopped,
    teamId: DEMO_IDS.teams.general,
    status: "resolved",
    detectedLanguage: "en",
    languageConfidence: 1,
    purpose: "general_support",
    handoffSummary: "Synthetic STOP event; marketing suppression recorded.",
    unreadCount: 0,
  },
];

function syntheticMessage(input: {
  id: Message["id"];
  conversationId: Message["conversationId"];
  contactId: Message["contactId"];
  preview: string;
  receivedAt: Message["receivedAt"];
}): Message {
  return {
    id: input.id,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    conversationId: input.conversationId,
    contactId: input.contactId,
    direction: "inbound",
    type: "text",
    status: "received",
    externalDispatch: "not_applicable",
    providerMessageId: `simulated-inbound:${input.id}`,
    templateVersionId: null,
    actorId: null,
    content: {
      safePreview: input.preview,
      protectedContentRef: null,
      containsClinicalContent: false,
      redactionApplied: false,
    },
    correlationId: correlationId(`demo-correlation:${input.id}`),
    requestId: requestId(`demo-request:${input.id}`),
    receivedAt: input.receivedAt,
    sentAt: null,
    deliveredAt: null,
    failureCode: null,
    synthetic: true,
    createdAt: input.receivedAt ?? DEMO_CLOCK.recent,
    updatedAt: input.receivedAt ?? DEMO_CLOCK.recent,
  };
}

export const demoMessages: readonly Message[] = [
  syntheticMessage({
    id: DEMO_IDS.messages.appointmentInbound,
    conversationId: DEMO_IDS.conversations.appointment,
    contactId: DEMO_IDS.contacts.appointment,
    preview: "Synthetic message: I would like to book a demo appointment.",
    receivedAt: DEMO_CLOCK.earlier,
  }),
  {
    id: DEMO_IDS.messages.appointmentReply,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    conversationId: DEMO_IDS.conversations.appointment,
    contactId: DEMO_IDS.contacts.appointment,
    direction: "outbound",
    type: "interactive",
    status: "simulated",
    externalDispatch: "simulation_only",
    providerMessageId: null,
    templateVersionId: null,
    actorId: null,
    content: {
      safePreview: "Simulation: choose a location to continue the appointment Flow.",
      protectedContentRef: null,
      containsClinicalContent: false,
      redactionApplied: false,
    },
    correlationId: correlationId("demo-correlation:appointment-reply"),
    requestId: requestId("demo-request:appointment-reply"),
    receivedAt: null,
    sentAt: DEMO_CLOCK.recent,
    deliveredAt: DEMO_CLOCK.recent,
    failureCode: null,
    synthetic: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
  syntheticMessage({
    id: DEMO_IDS.messages.laboratoryInbound,
    conversationId: DEMO_IDS.conversations.laboratory,
    contactId: DEMO_IDS.contacts.laboratory,
    preview: "කෘත්‍රිම පණිවිඩය: රසායනාගාර සේවාවක් ගැන දැනගැනීමට අවශ්‍යයි.",
    receivedAt: DEMO_CLOCK.recent,
  }),
  syntheticMessage({
    id: DEMO_IDS.messages.packageInbound,
    conversationId: DEMO_IDS.conversations.package,
    contactId: DEMO_IDS.contacts.package,
    preview: "செயற்கை செய்தி: ஒரு பரிசோதனைத் தொகுப்பு பற்றி அறிய விரும்புகிறேன்.",
    receivedAt: DEMO_CLOCK.recent,
  }),
  syntheticMessage({
    id: DEMO_IDS.messages.mixedInbound,
    conversationId: DEMO_IDS.conversations.mixedLanguage,
    contactId: DEMO_IDS.contacts.mixedLanguage,
    preview: "Synthetic mixed-language input — human review requested.",
    receivedAt: DEMO_CLOCK.recent,
  }),
  syntheticMessage({
    id: DEMO_IDS.messages.urgentInbound,
    conversationId: DEMO_IDS.conversations.urgent,
    contactId: DEMO_IDS.contacts.urgent,
    preview: "Synthetic urgent-language safety test — no clinical claim.",
    receivedAt: DEMO_CLOCK.recent,
  }),
  syntheticMessage({
    id: DEMO_IDS.messages.stopInbound,
    conversationId: DEMO_IDS.conversations.stopped,
    contactId: DEMO_IDS.contacts.stopped,
    preview: "STOP",
    receivedAt: DEMO_CLOCK.recent,
  }),
];

export const demoAppointments: readonly Appointment[] = [
  {
    id: DEMO_IDS.appointment,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    externalAppointmentRef: externalReference("DEMO-APT-0001"),
    contactId: DEMO_IDS.contacts.appointment,
    locationId: DEMO_IDS.locations.wattala,
    serviceRef: "demo-general-medicine",
    practitionerDisplayLabel: "Synthetic clinician schedule",
    slot: {
      startsAt: isoDateTime("2026-08-12T04:30:00.000Z"),
      endsAt: isoDateTime("2026-08-12T05:00:00.000Z"),
      timeZone: colombo,
    },
    status: "confirmed",
    syncState: "mock",
    idempotencyKey: "demo-appointment-request-0001",
    reminders: [
      {
        kind: "twenty_four_hour",
        scheduledFor: isoDateTime("2026-08-11T04:30:00.000Z"),
        status: "scheduled",
      },
      {
        kind: "two_hour",
        scheduledFor: isoDateTime("2026-08-12T02:30:00.000Z"),
        status: "scheduled",
      },
    ],
    authoritativeSystem: "simulator",
    lastSyncedAt: DEMO_CLOCK.recent,
    synthetic: true,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoLabReports: readonly LabReportMetadata[] = [
  {
    id: DEMO_IDS.labReport,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    externalReportRef: externalReference("DEMO-LAB-0001"),
    contactId: DEMO_IDS.contacts.laboratory,
    locationId: DEMO_IDS.locations.labNetwork,
    workflowStatus: "ready",
    collectedAt: isoDateTime("2026-08-06T03:30:00.000Z"),
    readyAt: DEMO_CLOCK.earlier,
    notificationIdempotencyKey: "demo-lims-ready-0001",
    secureAccess: {
      mode: "simulator",
      route: "/demo/secure-report/DEMO-LAB-0001",
      expiresAt: isoDateTime("2026-08-08T12:30:00.000Z"),
    },
    lastNotificationAt: null,
    authoritativeSystem: "simulator",
    synthetic: true,
    createdAt: isoDateTime("2026-08-06T03:30:00.000Z"),
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoTemplates: readonly MessageTemplate[] = [
  {
    id: DEMO_IDS.templates.appointment,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    providerName: "demo_appointment_confirmation",
    category: "utility",
    language: "en",
    activeVersionId: DEMO_IDS.templateVersions.appointment,
    safeNetOwned: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.templates.reportReady,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    providerName: "demo_report_ready",
    category: "utility",
    language: "si",
    activeVersionId: DEMO_IDS.templateVersions.reportReady,
    safeNetOwned: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.templates.campaign,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    providerName: "demo_health_awareness_campaign",
    category: "marketing",
    language: "en",
    activeVersionId: DEMO_IDS.templateVersions.campaign,
    safeNetOwned: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.templates.careCheckIn,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    providerName: "demo_care_check_in",
    category: "utility",
    language: "en",
    activeVersionId: DEMO_IDS.templateVersions.careCheckIn,
    safeNetOwned: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

function templateVersion(input: {
  id: MessageTemplateVersion["id"];
  templateId: MessageTemplateVersion["templateId"];
  body: string;
  variables: readonly MessageTemplateVersion["variableRules"][number][];
}): MessageTemplateVersion {
  return {
    id: input.id,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    templateId: input.templateId,
    version: 1,
    lifecycleState: "approved",
    approvalAuthority: "simulator",
    providerTemplateId: null,
    components: [{ kind: "body", text: input.body }],
    variableRules: input.variables,
    qualityRating: "unknown",
    qualityCheckedAt: null,
    immutable: true,
    rejectionReason: null,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  };
}

export const demoTemplateVersions: readonly MessageTemplateVersion[] = [
  templateVersion({
    id: DEMO_IDS.templateVersions.appointment,
    templateId: DEMO_IDS.templates.appointment,
    body: "Simulation: your appointment at {{location}} is confirmed for {{date_time}}. Reference {{reference}}.",
    variables: [
      { key: "location", description: "Approved location label", required: true, maxLength: 80, exampleValue: "Demo Hospital" },
      { key: "date_time", description: "Asia/Colombo date and time", required: true, maxLength: 48, exampleValue: "12 Aug 2026, 10:00" },
      { key: "reference", description: "Opaque booking reference", required: true, maxLength: 32, exampleValue: "DEMO-APT-0001" },
    ],
  }),
  templateVersion({
    id: DEMO_IDS.templateVersions.reportReady,
    templateId: DEMO_IDS.templates.reportReady,
    body: "Simulation: a laboratory report is ready. Sign in through the secure portal to view it. No result values are included here.",
    variables: [],
  }),
  templateVersion({
    id: DEMO_IDS.templateVersions.campaign,
    templateId: DEMO_IDS.templates.campaign,
    body: "Simulation: learn about the synthetic health-check package. Reply STOP to withdraw from marketing messages.",
    variables: [],
  }),
  templateVersion({
    id: DEMO_IDS.templateVersions.careCheckIn,
    templateId: DEMO_IDS.templates.careCheckIn,
    body: "Simulation: please answer the approved follow-up questions. This channel does not provide emergency care.",
    variables: [],
  }),
];

const audienceSummary = summarizeSyntheticAudience();
const audienceContentHash = sha256Digest("7a4d8ce2bc1bafc224e5e2b91a2fc3f8b20b5f062ff1563ca4cf25847ad0d550");

export const demoCampaign: Campaign = {
  id: DEMO_IDS.campaign,
  workspaceId: DEMO_IDS.workspaces.safeNet,
  name: "Synthetic 50,000-contact health-awareness simulation",
  purpose: "health_campaigns",
  messageCategory: "marketing",
  ownerId: DEMO_IDS.members.campaignOperator,
  targetAction: "Open a synthetic package enquiry",
  templateVersionId: DEMO_IDS.templateVersions.campaign,
  audienceSnapshotId: DEMO_IDS.audience,
  state: "scheduled",
  dispatchMode: "simulation",
  schedule: {
    startsAt: isoDateTime("2026-08-10T03:30:00.000Z"),
    timeZone: "Asia/Colombo",
    quietHours: { startsAtLocal: "20:00", endsAtLocal: "08:00" },
  },
  approval: {
    required: true,
    status: "approved",
    approverId: DEMO_IDS.members.campaignApprover,
    reviewedAt: DEMO_CLOCK.recent,
    approvedContentHash: audienceContentHash,
    comment: "Approved for simulator only. External sending remains disabled.",
  },
  allowlistTestStatus: "passed_simulation",
  estimatedUsageUnits: SYNTHETIC_CAMPAIGN_SIZE,
  synthetic: true,
  createdAt: DEMO_CLOCK.created,
  updatedAt: DEMO_CLOCK.recent,
};

export const demoAudienceSnapshot: AudienceSnapshot = {
  id: DEMO_IDS.audience,
  workspaceId: DEMO_IDS.workspaces.safeNet,
  campaignId: DEMO_IDS.campaign,
  criteriaSummary: "Synthetic adults with fixture marketing consent; exclusions are deterministic.",
  totalEvaluated: audienceSummary.totalEvaluated,
  eligibleCount: audienceSummary.eligibleCount,
  excludedCount: audienceSummary.excludedCount,
  unknownConsentCount: audienceSummary.unknownConsentCount,
  exclusionsByReason: audienceSummary.exclusionsByReason,
  languageCounts: audienceSummary.languageCounts,
  contentHash: audienceContentHash,
  finalizedAt: DEMO_CLOCK.recent,
  immutable: true,
  createdAt: DEMO_CLOCK.recent,
  updatedAt: DEMO_CLOCK.recent,
};

const automationStepPolicy = {
  requiredConsentPurpose: "appointment_service" as const,
  serviceWindowBehavior: "use_approved_template" as const,
  timeoutSeconds: 30,
  retry: { maxAttempts: 3, initialBackoffSeconds: 30, maximumBackoffSeconds: 900 },
  fallback: "create_work_item" as const,
};

export const demoAutomationDefinitions: readonly AutomationDefinition[] = [
  {
    id: DEMO_IDS.automationDefinition,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Synthetic appointment confirmation and reminder",
    trigger: "appointment_event",
    version: 1,
    consentPurpose: "appointment_service",
    steps: [
      {
        id: "send-confirmation",
        kind: "send_template",
        templateVersionId: DEMO_IDS.templateVersions.appointment,
        policy: automationStepPolicy,
      },
      { id: "wait-until-reminder", kind: "wait", waitSeconds: 79_200, policy: automationStepPolicy },
      {
        id: "request-confirmation-action",
        kind: "request_appointment_action",
        action: "confirm",
        policy: automationStepPolicy,
      },
    ],
    approvalState: "approved",
    approvedBy: DEMO_IDS.members.admin,
    approvedAt: DEMO_CLOCK.earlier,
    active: true,
    riskLevel: "medium",
    synthetic: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoAutomationRuns: readonly AutomationRun[] = [
  {
    id: DEMO_IDS.automationRun,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    definitionId: DEMO_IDS.automationDefinition,
    definitionVersion: 1,
    triggerEventId: "demo-appointment-confirmed-event-0001",
    idempotencyKey: "demo-run:appointment:0001:confirmation-v1",
    subject: {
      contactId: DEMO_IDS.contacts.appointment,
      conversationId: DEMO_IDS.conversations.appointment,
      appointmentId: DEMO_IDS.appointment,
    },
    state: "waiting",
    currentStepIndex: 1,
    completedStepIds: ["send-confirmation"],
    attemptCount: 1,
    nextAttemptAt: isoDateTime("2026-08-11T04:30:00.000Z"),
    lastMessageId: DEMO_IDS.messages.appointmentReply,
    lastErrorCode: null,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoCarePathways: readonly CarePathway[] = [
  {
    id: DEMO_IDS.carePathway,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    name: "Synthetic clinician-governed follow-up",
    protocolVersion: "demo-protocol-v1",
    clinicalOwnerId: DEMO_IDS.members.clinicalApprover,
    approvalState: "approved",
    approvedBy: DEMO_IDS.members.clinicalApprover,
    approvedAt: DEMO_CLOCK.earlier,
    contactDayOffsets: [1, 3, 7],
    responseSlaMinutes: 15,
    escalationTeamId: DEMO_IDS.teams.clinicalEscalation,
    afterHoursBehavior: "emergency_path",
    writeBackRequired: true,
    instructionsSource: "clinician_authored",
    aiMayGenerateInstructions: false,
    synthetic: true,
    createdAt: DEMO_CLOCK.created,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoCareEnrollments: readonly CarePathwayEnrollment[] = [
  {
    id: DEMO_IDS.careEnrollment,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    pathwayId: DEMO_IDS.carePathway,
    pathwayProtocolVersion: "demo-protocol-v1",
    contactId: DEMO_IDS.contacts.urgent,
    externalDischargeRef: externalReference("DEMO-DISCHARGE-0001"),
    enrolledAt: DEMO_CLOCK.earlier,
    state: "escalated",
    suppressionReasons: ["clinical_hold"],
    nextContactAt: null,
    synthetic: true,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoAuditEvents: readonly AuditEvent[] = [
  {
    id: DEMO_IDS.audit.workspaceViewed,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    actor: { type: "member", memberId: DEMO_IDS.members.admin, uid: DEMO_IDS.users.admin },
    action: "workspace.viewed",
    target: { collection: "workspace", id: DEMO_IDS.workspaces.safeNet },
    requestId: requestId("demo-audit-request-workspace-viewed"),
    outcome: "success",
    metadata: { synthetic: true, environment: "demo" },
    occurredAt: DEMO_CLOCK.earlier,
    immutable: true,
    createdAt: DEMO_CLOCK.earlier,
    updatedAt: DEMO_CLOCK.earlier,
  },
  {
    id: DEMO_IDS.audit.stopRecorded,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    actor: { type: "system", service: "consent-simulator" },
    action: "consent.marketing_withdrawn",
    target: { collection: "contacts", id: DEMO_IDS.contacts.stopped },
    requestId: requestId("demo-audit-request-stop-recorded"),
    outcome: "success",
    metadata: { source: "inbound_keyword", category: "marketing", synthetic: true },
    occurredAt: DEMO_CLOCK.recent,
    immutable: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.audit.campaignApproved,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    actor: {
      type: "member",
      memberId: DEMO_IDS.members.campaignApprover,
      uid: DEMO_IDS.users.campaignApprover,
    },
    action: "campaign.simulation_approved",
    target: { collection: "campaigns", id: DEMO_IDS.campaign },
    requestId: requestId("demo-audit-request-campaign-approved"),
    outcome: "success",
    metadata: { dispatchMode: "simulation", audienceSize: SYNTHETIC_CAMPAIGN_SIZE },
    occurredAt: DEMO_CLOCK.recent,
    immutable: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoUsageLedger: readonly UsageLedgerEntry[] = [
  {
    id: DEMO_IDS.usage.inbound,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    connectionId: DEMO_IDS.connections.simulator,
    type: "inbound_message",
    quantity: 6,
    unit: "count",
    provider: "simulator",
    referenceType: "demo-session",
    referenceId: "demo-session-2026-08-07",
    occurredAt: DEMO_CLOCK.recent,
    synthetic: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
  {
    id: DEMO_IDS.usage.simulatedCampaign,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    connectionId: DEMO_IDS.connections.simulator,
    type: "queue_job",
    quantity: audienceSummary.eligibleCount,
    unit: "job",
    provider: "simulator",
    referenceType: "campaign",
    referenceId: DEMO_IDS.campaign,
    occurredAt: DEMO_CLOCK.recent,
    synthetic: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoDailyMetrics: readonly DailyMetric[] = [
  {
    id: DEMO_IDS.metric,
    workspaceId: DEMO_IDS.workspaces.safeNet,
    date: isoDate("2026-08-07"),
    metricVersion: "demo-metric-v1",
    dimension: "conversation",
    counts: {
      active: 4,
      assigned: 1,
      escalated: 1,
      resolved: 1,
      syntheticCampaignEligible: audienceSummary.eligibleCount,
    },
    sampleData: true,
    createdAt: DEMO_CLOCK.recent,
    updatedAt: DEMO_CLOCK.recent,
  },
];

export const demoFixtureBundle = {
  workspaces: demoWorkspaces,
  staffIdentities: demoStaffIdentities,
  memberships: demoMemberships,
  teams: demoTeams,
  locations: demoLocations,
  connections: demoConnections,
  contacts: demoContacts,
  consentRecords: demoConsentRecords,
  conversations: demoConversations,
  messages: demoMessages,
  appointments: demoAppointments,
  labReports: demoLabReports,
  templates: demoTemplates,
  templateVersions: demoTemplateVersions,
  campaigns: [demoCampaign],
  audienceSnapshots: [demoAudienceSnapshot],
  automationDefinitions: demoAutomationDefinitions,
  automationRuns: demoAutomationRuns,
  carePathways: demoCarePathways,
  careEnrollments: demoCareEnrollments,
  auditEvents: demoAuditEvents,
  usageLedger: demoUsageLedger,
  dailyMetrics: demoDailyMetrics,
} as const;
