import {
  entityId,
  type AppointmentId,
  type AudienceSnapshotId,
  type AuditEventId,
  type AutomationDefinitionId,
  type AutomationRunId,
  type CampaignId,
  type CareEnrollmentId,
  type CarePathwayId,
  type ConnectionId,
  type ConsentRecordId,
  type ContactId,
  type ConversationId,
  type DailyMetricId,
  type LabReportId,
  type LocationId,
  type MemberId,
  type MessageId,
  type TeamId,
  type TemplateId,
  type TemplateVersionId,
  type UsageLedgerId,
  type UserId,
  type WorkspaceId,
} from "../domain/primitives";

export const DEMO_IDS = {
  workspaces: {
    safeNet: entityId<"Workspace">("workspace_safenet_demo") as WorkspaceId,
    hemasLocked: entityId<"Workspace">("workspace_hemas_locked") as WorkspaceId,
  },
  users: {
    admin: entityId<"User">("user_demo_admin") as UserId,
    supervisor: entityId<"User">("user_demo_supervisor") as UserId,
    agent: entityId<"User">("user_demo_agent") as UserId,
    campaignOperator: entityId<"User">("user_demo_campaign_operator") as UserId,
    campaignApprover: entityId<"User">("user_demo_campaign_approver") as UserId,
    privacyReviewer: entityId<"User">("user_demo_privacy_reviewer") as UserId,
    clinicalApprover: entityId<"User">("user_demo_clinical_approver") as UserId,
  },
  members: {
    admin: entityId<"Member">("member_demo_admin") as MemberId,
    supervisor: entityId<"Member">("member_demo_supervisor") as MemberId,
    agent: entityId<"Member">("member_demo_agent") as MemberId,
    campaignOperator: entityId<"Member">("member_demo_campaign_operator") as MemberId,
    campaignApprover: entityId<"Member">("member_demo_campaign_approver") as MemberId,
    privacyReviewer: entityId<"Member">("member_demo_privacy_reviewer") as MemberId,
    clinicalApprover: entityId<"Member">("member_demo_clinical_approver") as MemberId,
  },
  teams: {
    general: entityId<"Team">("team_demo_general") as TeamId,
    laboratory: entityId<"Team">("team_demo_laboratory") as TeamId,
    clinicalEscalation: entityId<"Team">("team_demo_clinical_escalation") as TeamId,
  },
  locations: {
    wattala: entityId<"Location">("location_demo_wattala") as LocationId,
    thalawathugoda: entityId<"Location">("location_demo_thalawathugoda") as LocationId,
    labNetwork: entityId<"Location">("location_demo_lab_network") as LocationId,
  },
  connections: {
    simulator: entityId<"Connection">("connection_demo_simulator") as ConnectionId,
    hemasLocked: entityId<"Connection">("connection_hemas_locked") as ConnectionId,
  },
  contacts: {
    appointment: entityId<"Contact">("contact_synthetic_appointment") as ContactId,
    laboratory: entityId<"Contact">("contact_synthetic_laboratory") as ContactId,
    package: entityId<"Contact">("contact_synthetic_package") as ContactId,
    mixedLanguage: entityId<"Contact">("contact_synthetic_mixed") as ContactId,
    urgent: entityId<"Contact">("contact_synthetic_urgent") as ContactId,
    stopped: entityId<"Contact">("contact_synthetic_stopped") as ContactId,
  },
  consents: {
    appointment: entityId<"ConsentRecord">("consent_synthetic_appointment") as ConsentRecordId,
    laboratory: entityId<"ConsentRecord">("consent_synthetic_laboratory") as ConsentRecordId,
    packageMarketing: entityId<"ConsentRecord">("consent_synthetic_package_marketing") as ConsentRecordId,
    stoppedGranted: entityId<"ConsentRecord">("consent_synthetic_stop_granted") as ConsentRecordId,
    stoppedWithdrawn: entityId<"ConsentRecord">("consent_synthetic_stop_withdrawn") as ConsentRecordId,
    carePathway: entityId<"ConsentRecord">("consent_synthetic_care_pathway") as ConsentRecordId,
  },
  conversations: {
    appointment: entityId<"Conversation">("conversation_synthetic_appointment") as ConversationId,
    laboratory: entityId<"Conversation">("conversation_synthetic_laboratory") as ConversationId,
    package: entityId<"Conversation">("conversation_synthetic_package") as ConversationId,
    mixedLanguage: entityId<"Conversation">("conversation_synthetic_mixed") as ConversationId,
    urgent: entityId<"Conversation">("conversation_synthetic_urgent") as ConversationId,
    phase5Care: entityId<"Conversation">("conversation_synthetic_phase5_care") as ConversationId,
    stopped: entityId<"Conversation">("conversation_synthetic_stopped") as ConversationId,
  },
  messages: {
    appointmentInbound: entityId<"Message">("message_synthetic_appointment_inbound") as MessageId,
    appointmentReply: entityId<"Message">("message_synthetic_appointment_reply") as MessageId,
    laboratoryInbound: entityId<"Message">("message_synthetic_laboratory_inbound") as MessageId,
    packageInbound: entityId<"Message">("message_synthetic_package_inbound") as MessageId,
    mixedInbound: entityId<"Message">("message_synthetic_mixed_inbound") as MessageId,
    urgentInbound: entityId<"Message">("message_synthetic_urgent_inbound") as MessageId,
    stopInbound: entityId<"Message">("message_synthetic_stop_inbound") as MessageId,
  },
  appointment: entityId<"Appointment">("appointment_synthetic_001") as AppointmentId,
  labReport: entityId<"LabReport">("lab_report_synthetic_001") as LabReportId,
  templates: {
    appointment: entityId<"Template">("template_synthetic_appointment") as TemplateId,
    reportReady: entityId<"Template">("template_synthetic_report_ready") as TemplateId,
    campaign: entityId<"Template">("template_synthetic_campaign") as TemplateId,
    careCheckIn: entityId<"Template">("template_synthetic_care_checkin") as TemplateId,
  },
  templateVersions: {
    appointment: entityId<"TemplateVersion">("template_version_synthetic_appointment_v1") as TemplateVersionId,
    reportReady: entityId<"TemplateVersion">("template_version_synthetic_report_ready_v1") as TemplateVersionId,
    campaign: entityId<"TemplateVersion">("template_version_synthetic_campaign_v1") as TemplateVersionId,
    careCheckIn: entityId<"TemplateVersion">("template_version_synthetic_care_checkin_v1") as TemplateVersionId,
  },
  campaign: entityId<"Campaign">("campaign_synthetic_50k") as CampaignId,
  audience: entityId<"AudienceSnapshot">("audience_synthetic_50k_v1") as AudienceSnapshotId,
  automationDefinition: entityId<"AutomationDefinition">("automation_synthetic_appointment_v1") as AutomationDefinitionId,
  automationRun: entityId<"AutomationRun">("automation_run_synthetic_appointment_001") as AutomationRunId,
  carePathway: entityId<"CarePathway">("care_pathway_synthetic_followup_v1") as CarePathwayId,
  careEnrollment: entityId<"CareEnrollment">("care_enrollment_synthetic_001") as CareEnrollmentId,
  audit: {
    workspaceViewed: entityId<"AuditEvent">("audit_synthetic_workspace_viewed") as AuditEventId,
    stopRecorded: entityId<"AuditEvent">("audit_synthetic_stop_recorded") as AuditEventId,
    campaignApproved: entityId<"AuditEvent">("audit_synthetic_campaign_approved") as AuditEventId,
  },
  usage: {
    inbound: entityId<"UsageLedger">("usage_synthetic_inbound") as UsageLedgerId,
    simulatedCampaign: entityId<"UsageLedger">("usage_synthetic_campaign") as UsageLedgerId,
  },
  metric: entityId<"DailyMetric">("metric_synthetic_daily_2026_08_07") as DailyMetricId,
} as const;
