import {
  BarChart3,
  Bot,
  Boxes,
  BriefcaseMedical,
  CircleDollarSign,
  ContactRound,
  FileCheck2,
  FlaskConical,
  HelpCircle,
  Inbox,
  Network,
  Settings,
  ShieldCheck,
  UsersRound,
  Workflow,
} from "lucide-react";
import type { ModuleConfig } from "@/components/module-scaffold";

const standardChecks = [
  { label: "Synthetic data only", value: "Enforced", ready: true },
  { label: "External provider calls", value: "Disabled", ready: true },
  { label: "Production workspace", value: "Locked", ready: false },
];

export const moduleConfigs: Record<string, ModuleConfig> = {
  inbox: {
    eyebrow: "Patient operations", title: "Shared inbox", icon: Inbox,
    description: "Route multilingual synthetic conversations, inspect safety signals, and demonstrate explicit human takeover without sending a real message.",
    actionLabel: "New outbound message", actionDisabled: true,
    metrics: [
      { label: "Open", value: "28", detail: "Across four synthetic queues" },
      { label: "Unassigned", value: "6", detail: "Oldest sample wait: 14 minutes" },
      { label: "Human takeover", value: "4", detail: "AI is paused for these records" },
      { label: "Urgent escalations", value: "3", detail: "Supervisor routing demonstrated" },
    ],
    table: { title: "Conversation queue", description: "Masked references and generated content only", columns: ["Conversation", "Queue", "Last activity", "State"], rows: [
      { primary: "SYN-C009 · தமிழ்", secondary: "Urgent escalation", third: "2 minutes ago", status: "Escalated", tone: "danger" },
      { primary: "SYN-C014 · English", secondary: "Appointments", third: "7 minutes ago", status: "Human", tone: "info" },
      { primary: "SYN-C021 · සිංහල", secondary: "Laboratory", third: "11 minutes ago", status: "Waiting", tone: "warning" },
      { primary: "SYN-C027 · English", secondary: "General enquiries", third: "18 minutes ago", status: "AI draft", tone: "success" },
    ]},
    guardrail: { title: "Conversation safeguards", description: "Human override, urgent-language routing, and suppression checks run before any response simulation.", checks: [...standardChecks, { label: "Clinical advice", value: "Blocked", ready: true }], href: "/ai-knowledge", linkLabel: "Review AI policy" },
  },
  contacts: {
    eyebrow: "Consent & preferences", title: "Contacts", icon: ContactRound,
    description: "Manage purpose-specific consent, communication preferences, suppressions, and masked external references in a tenant-scoped workspace.",
    actionLabel: "Add synthetic contact", actionHref: "/demo-lab",
    metrics: [
      { label: "Synthetic contacts", value: "50,000", detail: "Deterministic test cohort" },
      { label: "Marketing eligible", value: "38,443", detail: "Deterministic sample snapshot" },
      { label: "Suppressed", value: "2,413", detail: "STOP and governance exclusions" },
      { label: "Preferences due", value: "184", detail: "Synthetic renewal workflow" },
    ],
    table: { title: "Contact directory", description: "No names, phone numbers, or patient records are present", columns: ["Reference", "Language", "Consent purpose", "State"], rows: [
      { primary: "SYN-P000184", secondary: "Tamil", third: "Appointment utility", status: "Eligible", tone: "success" },
      { primary: "SYN-P000862", secondary: "Sinhala", third: "Service updates", status: "Eligible", tone: "success" },
      { primary: "SYN-P001204", secondary: "English", third: "Wellness marketing", status: "Suppressed", tone: "danger" },
      { primary: "SYN-P002781", secondary: "Tamil", third: "Lab notification", status: "Review due", tone: "warning" },
    ]},
    guardrail: { title: "Consent posture", description: "A derived summary supports fast eligibility; immutable evidence records remain append-only and purpose-specific.", checks: [...standardChecks, { label: "Unrestricted CSV import", value: "Blocked", ready: true }], href: "/compliance", linkLabel: "Open consent oversight" },
  },
  appointments: {
    eyebrow: "Care access", title: "Appointments", icon: BriefcaseMedical,
    description: "Demonstrate booking, confirmation, reminder, reschedule, and cancellation journeys against a mock authoritative scheduling adapter.",
    actionLabel: "Book mock appointment", actionHref: "/demo-lab",
    metrics: [
      { label: "Today", value: "42", detail: "Generated mock schedule" },
      { label: "Confirmed", value: "31", detail: "No HIS write has occurred" },
      { label: "Awaiting reply", value: "7", detail: "Utility templates simulated" },
      { label: "Rescheduled", value: "4", detail: "Idempotent demo events" },
    ],
    table: { title: "Upcoming mock appointments", description: "Availability is generated locally and never presented as real", columns: ["Reference", "Location / service", "Scheduled", "State"], rows: [
      { primary: "SYN-A1842", secondary: "Wattala · General medicine", third: "Today · 10:30", status: "Confirmed", tone: "success" },
      { primary: "SYN-A1874", secondary: "Thalawathugoda · Paediatrics", third: "Today · 11:15", status: "Reply due", tone: "warning" },
      { primary: "SYN-A1901", secondary: "Wattala · Cardiology", third: "Today · 13:00", status: "Rescheduled", tone: "info" },
      { primary: "SYN-A1933", secondary: "Thalawathugoda · OPD", third: "Tomorrow · 09:00", status: "Cancelled", tone: "neutral" },
    ]},
    guardrail: { title: "Source-of-truth boundary", description: "A production journey must revalidate every slot in Hemas' authoritative system before confirming it.", checks: [...standardChecks, { label: "HIS write-back", value: "Not connected", ready: false }], href: "/connections", linkLabel: "View adapter gates" },
  },
  labs: {
    eyebrow: "Secure notifications", title: "Laboratory journeys", icon: FlaskConical,
    description: "Model report-ready notifications and home-collection requests while keeping results and clinical interpretation outside the messaging platform.",
    actionLabel: "Run lab scenario", actionHref: "/demo-lab",
    metrics: [
      { label: "Report-ready jobs", value: "18", detail: "Synthetic metadata only" },
      { label: "Notification queued", value: "12", detail: "External dispatch is disabled" },
      { label: "Secure-link opened", value: "5", detail: "Mock access events" },
      { label: "Needs assistance", value: "1", detail: "Routed to a human queue" },
    ],
    table: { title: "Lab notification jobs", description: "No result values, diagnoses, or raw reports are stored", columns: ["Job", "Journey", "Ready time", "State"], rows: [
      { primary: "SYN-L0041", secondary: "Report-ready notification", third: "09:42", status: "Queued", tone: "warning" },
      { primary: "SYN-L0040", secondary: "Secure portal handoff", third: "09:31", status: "Opened", tone: "success" },
      { primary: "SYN-L0039", secondary: "Home collection request", third: "09:08", status: "Scheduled", tone: "info" },
      { primary: "SYN-L0038", secondary: "Report-ready notification", third: "08:54", status: "Human help", tone: "neutral" },
    ]},
    guardrail: { title: "Clinical data boundary", description: "Messages may announce readiness and provide a secure portal handoff. They must never include or interpret a result.", checks: [...standardChecks, { label: "Report values in chat", value: "Prohibited", ready: true }], href: "/compliance", linkLabel: "Review data controls" },
  },
  campaigns: {
    eyebrow: "Governed engagement", title: "Campaigns", icon: Boxes,
    description: "Build immutable synthetic audiences, enforce purpose-specific consent, separate creator and approver duties, and simulate rate-controlled delivery.",
    actionLabel: "Create campaign draft", actionHref: "/demo-lab",
    metrics: [
      { label: "Drafts", value: "3", detail: "Synthetic content only" },
      { label: "Pending approval", value: "1", detail: "Independent review required" },
      { label: "Eligible audience", value: "38,443", detail: "From the deterministic 50K cohort" },
      { label: "External sends", value: "0", detail: "Provider adapter is fail-closed" },
    ],
    table: { title: "Campaign control", description: "Dispatch values are simulation results, not Meta delivery claims", columns: ["Campaign", "Audience", "Schedule", "State"], rows: [
      { primary: "50K Wellness Awareness", secondary: "38,443 eligible", third: "Simulation only", status: "Approval ready", tone: "info" },
      { primary: "Dengue prevention education", secondary: "12,480 eligible", third: "Draft", status: "Draft", tone: "neutral" },
      { primary: "Maternity service updates", secondary: "3,214 eligible", third: "Paused sample", status: "Safeguard pause", tone: "warning" },
      { primary: "Health-check package", secondary: "8,902 eligible", third: "Not scheduled", status: "Consent review", tone: "danger" },
    ]},
    guardrail: { title: "Launch controls", description: "One UI launch becomes governed batches, recipient-level eligibility checks, canary monitoring, and pauseable work.", checks: [...standardChecks, { label: "Independent approval", value: "Required", ready: true }, { label: "Meta capacity", value: "Unknown", ready: false }], href: "/compliance", linkLabel: "Review approval evidence" },
  },
  templates: {
    eyebrow: "Approved content", title: "Templates & WhatsApp Flows", icon: FileCheck2,
    description: "Version utility and marketing content, preview multilingual variants, and design in-chat forms without claiming Meta publication or approval.",
    actionLabel: "Create draft version", actionHref: "/demo-lab",
    metrics: [
      { label: "Template drafts", value: "14", detail: "Local preview catalogue" },
      { label: "Flow drafts", value: "6", detail: "Booking, lab, package, feedback" },
      { label: "Meta approved", value: "0", detail: "No Meta account connected" },
      { label: "Languages", value: "3", detail: "English, Tamil, Sinhala" },
    ],
    table: { title: "Content catalogue", description: "Statuses describe local governance only unless explicitly marked Meta-synced", columns: ["Asset", "Locale / category", "Version", "State"], rows: [
      { primary: "appointment_confirmation", secondary: "English · Utility", third: "v3", status: "Locally approved", tone: "success" },
      { primary: "lab_report_ready", secondary: "Tamil · Utility", third: "v2", status: "Clinical review", tone: "warning" },
      { primary: "doctor_booking_flow", secondary: "Trilingual · Flow", third: "v1", status: "Demo ready", tone: "info" },
      { primary: "wellness_awareness", secondary: "Sinhala · Marketing", third: "v4", status: "Draft", tone: "neutral" },
    ]},
    guardrail: { title: "Publication boundary", description: "Local approval never means Meta approval. Hemas production assets must be recreated and approved under Hemas ownership.", checks: [...standardChecks, { label: "Meta template sync", value: "Unavailable", ready: false }], href: "/connections", linkLabel: "View Meta prerequisites" },
  },
  automations: {
    eyebrow: "Governed workflows", title: "Automations & care paths", icon: Workflow,
    description: "Version event-driven reminders and clinician-governed follow-up pathways with quiet hours, red-flag escalation, and explicit approval states.",
    actionLabel: "Create workflow draft", actionHref: "/demo-lab",
    metrics: [
      { label: "Active simulations", value: "8", detail: "Local events only" },
      { label: "Care-path drafts", value: "3", detail: "Clinical approval required" },
      { label: "Escalations today", value: "2", detail: "Synthetic red flags" },
      { label: "Provider writes", value: "0", detail: "All adapters disabled" },
    ],
    table: { title: "Workflow catalogue", description: "Every published version is immutable and approval-bound", columns: ["Workflow", "Trigger", "Last run", "State"], rows: [
      { primary: "Appointment reminder sequence", secondary: "Appointment confirmed", third: "10 minutes ago", status: "Simulating", tone: "success" },
      { primary: "Post-discharge check-in", secondary: "Mock discharge event", third: "24 minutes ago", status: "Clinical review", tone: "warning" },
      { primary: "Lab-ready notification", secondary: "Mock LIMS event", third: "31 minutes ago", status: "Simulating", tone: "success" },
      { primary: "Feedback request", secondary: "Visit completed", third: "1 hour ago", status: "Draft", tone: "neutral" },
    ]},
    guardrail: { title: "Care-path governance", description: "The system collects structured check-ins and escalates red flags; it does not diagnose, treat, or replace clinical care.", checks: [...standardChecks, { label: "Clinical content approval", value: "Required", ready: true }], href: "/ai-knowledge", linkLabel: "Review clinical boundaries" },
  },
  analytics: {
    eyebrow: "Sample reporting", title: "Analytics", icon: BarChart3,
    description: "Inspect pseudonymised sample operations, journey outcomes, safety events, and campaign simulations without exposing message bodies or identities.",
    actionLabel: "Create saved view", actionHref: "/demo-lab",
    metrics: [
      { label: "Median first response", value: "2m 18s", detail: "Generated sample period" },
      { label: "Resolved in channel", value: "68%", detail: "Not a production claim" },
      { label: "Human handoff", value: "22%", detail: "Sample safety behavior" },
      { label: "Safety blocks", value: "3.4%", detail: "Synthetic prompts" },
    ],
    table: { title: "Journey performance", description: "All values are labelled sample analytics", columns: ["Journey", "Volume", "Outcome", "State"], rows: [
      { primary: "Appointment enquiry", secondary: "1,284 samples", third: "71% mock completion", status: "Sample", tone: "info" },
      { primary: "Lab report-ready", secondary: "642 samples", third: "84% portal handoff", status: "Sample", tone: "info" },
      { primary: "General enquiry", secondary: "2,104 samples", third: "63% resolved", status: "Sample", tone: "info" },
      { primary: "Urgent language", secondary: "38 samples", third: "100% escalated", status: "Safeguard", tone: "success" },
    ]},
    guardrail: { title: "Privacy-preserving analytics", description: "Analysts receive aggregates by default. Message bodies and direct identifiers are excluded from reporting views.", checks: [...standardChecks, { label: "Direct identifiers", value: "Excluded", ready: true }], href: "/compliance", linkLabel: "Review reporting access" },
  },
  ai: {
    eyebrow: "Assisted service", title: "AI & Knowledge", icon: Bot,
    description: "Govern language detection, intent routing, approved-knowledge retrieval, response drafting, policy review, and mandatory human escalation.",
    actionLabel: "Add knowledge draft", actionHref: "/demo-lab",
    metrics: [
      { label: "Approved sources", value: "12", detail: "Synthetic policy content" },
      { label: "Draft sources", value: "4", detail: "Not available to the assistant" },
      { label: "Low-confidence handoffs", value: "17", detail: "Generated sample period" },
      { label: "Clinical interpretations", value: "0", detail: "Blocked by design" },
    ],
    table: { title: "Knowledge governance", description: "Only approved, effective sources can support a response draft", columns: ["Source", "Owner", "Effective window", "State"], rows: [
      { primary: "Appointment service guide", secondary: "Operations", third: "Current sample", status: "Approved", tone: "success" },
      { primary: "Laboratory notification policy", secondary: "Clinical governance", third: "Current sample", status: "Approved", tone: "success" },
      { primary: "Package information draft", secondary: "Marketing", third: "Not effective", status: "Review", tone: "warning" },
      { primary: "Urgent-language response", secondary: "Clinical governance", third: "Current sample", status: "Approved", tone: "success" },
    ]},
    guardrail: { title: "Hard AI boundaries", description: "Diagnosis, medication advice, treatment recommendations, report interpretation, invented availability, and unsupervised mutations are prohibited.", checks: [...standardChecks, { label: "Human override", value: "Always on", ready: true }, { label: "Diagnosis tools", value: "None", ready: true }], href: "/demo-lab", linkLabel: "Test a safe scenario" },
  },
  connections: {
    eyebrow: "Authoritative local catalogue", title: "Connections", icon: Network,
    description: "Read the strict staff-safe simulator catalogue through three fixed local Firestore server reads without cache, fixture, mutation, credential, or provider-control fallbacks.",
    actionLabel: "Connection changes unavailable", actionDisabled: true,
    metrics: [
      { label: "Inventory source", value: "Persisted", detail: "Authoritative local server reads" },
      { label: "Browser writes", value: "0", detail: "Read-only catalogue policy" },
      { label: "External sending", value: "Off", detail: "Frozen persisted false gate" },
      { label: "Fallback sources", value: "0", detail: "No cache or fixture inventory" },
    ],
    table: { title: "Catalogue read boundary", description: "Entity counts appear only after strict persisted v1 validation", columns: ["Surface", "Read shape", "Fallback", "State"], rows: [
      { primary: "WhatsApp simulator projection", secondary: "One fixed document", third: "None", status: "Authoritative read", tone: "info" },
      { primary: "Appointment simulator projection", secondary: "One fixed document", third: "None", status: "Authoritative read", tone: "info" },
      { primary: "Laboratory simulator projection", secondary: "One fixed document", third: "None", status: "Authoritative read", tone: "info" },
      { primary: "Secrets and raw identifiers", secondary: "No browser path", third: "None", status: "Excluded", tone: "neutral" },
    ]},
    guardrail: { title: "Zero-network boundary", description: "Persisted simulator rows are not evidence of any external connection, delivery, authoritative write, cloud deployment, or acceptance.", checks: [{ label: "External messaging", value: "False", ready: true }, { label: "External network", value: "False", ready: true }, { label: "Authoritative writes", value: "False", ready: true }, { label: "Real-device evidence", value: "None", ready: false }], href: "/compliance", linkLabel: "Review governance boundary" },
  },
  team: {
    eyebrow: "Least-privilege access", title: "Team & Routing", icon: UsersRound,
    description: "Model workspace roles, department and location scopes, queue assignment, SLAs, and segregation of duties using fail-closed access rules.",
    actionLabel: "Invite team member", actionDisabled: true,
    metrics: [
      { label: "Demo members", value: "9", detail: "Synthetic identities only" },
      { label: "Queues", value: "4", detail: "Sample routing setup" },
      { label: "Unscoped agents", value: "0", detail: "Empty scope means no access" },
      { label: "MFA-required roles", value: "6", detail: "Production policy modeled" },
    ],
    table: { title: "Demo membership", description: "Roles cannot be self-assigned or changed from the browser", columns: ["Member", "Role", "Scope", "State"], rows: [
      { primary: "Synthetic Admin 01", secondary: "Workspace administrator", third: "Demo workspace", status: "Active", tone: "success" },
      { primary: "Synthetic Agent 04", secondary: "Agent", third: "Appointments · Wattala", status: "Active", tone: "success" },
      { primary: "Synthetic Reviewer 02", secondary: "Clinical approver", third: "Clinical content", status: "Active", tone: "success" },
      { primary: "Synthetic Analyst 01", secondary: "Analyst", third: "Aggregates only", status: "Restricted", tone: "info" },
    ]},
    guardrail: { title: "Authorization posture", description: "Tenant, role, department, and location checks must agree across Security Rules and server APIs. Empty operational scopes fail closed.", checks: [...standardChecks, { label: "Self-service role changes", value: "Denied", ready: true }], href: "/compliance", linkLabel: "View audit coverage" },
  },
  compliance: {
    eyebrow: "Privacy & accountability", title: "Compliance & Audit", icon: ShieldCheck,
    description: "Review synthetic-stage controls, a role-restricted minimized audit projection, retention decisions, and unresolved production governance gates.",
    actionLabel: "Review release gates", actionHref: "/compliance",
    metrics: [
      { label: "Timeline access", value: "Role-gated", detail: "Privacy reviewer or workspace-wide admin" },
      { label: "Raw browser list", value: "Denied", detail: "Callable projection only" },
      { label: "Exports", value: "Locked", detail: "No production export workflow" },
      { label: "Production approvals", value: "0", detail: "No sign-offs claimed" },
    ],
    table: { title: "Audit access boundary", description: "No fabricated event rows or completeness claim", columns: ["Surface", "Authority", "Evidence", "State"], rows: [
      { primary: "Control register", secondary: "audit.view roles", third: "Static governance plan", status: "Available", tone: "success" },
      { primary: "Minimized timeline", secondary: "Privacy reviewer / workspace-wide admin", third: "Local callable projection", status: "Restricted", tone: "info" },
      { primary: "Raw audit collection", secondary: "Browser", third: "No list request", status: "Denied", tone: "danger" },
      { primary: "Production export", secondary: "No approved workflow", third: "No connected destination", status: "Locked", tone: "warning" },
    ]},
    guardrail: { title: "Production governance", description: "A DPIA, data map, lawful processing decisions, retention schedule, contracts, security review, and Hemas approvals remain mandatory.", checks: [{ label: "Prototype rules", value: "In review", ready: true }, { label: "DPIA", value: "Not completed", ready: false }, { label: "Clinical sign-off", value: "Not completed", ready: false }, { label: "Hemas DPO sign-off", value: "Not completed", ready: false }], href: "/connections", linkLabel: "View activation status" },
  },
  usage: {
    eyebrow: "Commercial visibility", title: "Usage", icon: CircleDollarSign,
    description: "Estimate provider and infrastructure usage from synthetic events while clearly separating sample costs from actual Meta or Google invoices.",
    actionLabel: "Set sample budget", actionHref: "/settings",
    metrics: [
      { label: "Simulated messages", value: "50,000", detail: "No provider requests made" },
      { label: "Estimated Meta cost", value: "Not quoted", detail: "Pricing requires current verification" },
      { label: "Firebase usage", value: "Local", detail: "Emulators do not create cloud charges" },
      { label: "Budget alerts", value: "3", detail: "Sample thresholds" },
    ],
    table: { title: "Synthetic usage ledger", description: "Values prove accounting behavior, not a bill", columns: ["Operation", "Quantity", "Period", "State"], rows: [
      { primary: "Campaign recipient simulation", secondary: "50,000 operations", third: "Current demo run", status: "No charge", tone: "success" },
      { primary: "AI safety review", secondary: "2,418 operations", third: "Sample month", status: "Estimated", tone: "info" },
      { primary: "Firestore writes", secondary: "82,140 operations", third: "Local emulator", status: "Local", tone: "success" },
      { primary: "Secure-link events", secondary: "642 operations", third: "Sample month", status: "Simulated", tone: "neutral" },
    ]},
    guardrail: { title: "Cost truth boundary", description: "Actual costs depend on current Meta pricing, message category, recipient market, provider choices, Google region, and live volume.", checks: [...standardChecks, { label: "Live billing account", value: "None", ready: true }], href: "/analytics", linkLabel: "View sample volumes" },
  },
  settings: {
    eyebrow: "Workspace configuration", title: "Settings", icon: Settings,
    description: "Inspect environment, language, timezone, feature-flag, retention, and notification defaults with production-sensitive controls locked.",
    actionLabel: "Create setting draft", actionHref: "/demo-lab",
    metrics: [
      { label: "Environment", value: "Demo", detail: "Persistent non-production label" },
      { label: "Timezone", value: "Asia/Colombo", detail: "UTC retained for storage" },
      { label: "Languages", value: "3", detail: "English, Tamil, Sinhala" },
      { label: "External messaging", value: "Off", detail: "Fail-closed configuration" },
    ],
    table: { title: "Configuration summary", description: "Sensitive values and secret material never appear here", columns: ["Setting", "Value", "Source", "State"], rows: [
      { primary: "Application stage", secondary: "demo", third: "App Hosting environment", status: "Locked", tone: "success" },
      { primary: "External messaging", secondary: "false", third: "Fail-closed flag", status: "Locked", tone: "success" },
      { primary: "Real patient data", secondary: "false", third: "Fail-closed flag", status: "Locked", tone: "success" },
      { primary: "Production data region", secondary: "Undecided", third: "Hemas governance decision", status: "Open decision", tone: "warning" },
    ]},
    guardrail: { title: "Sensitive configuration", description: "A browser setting cannot activate providers. Secrets belong in Secret Manager and production activation requires server-side, approval-bound gates.", checks: [...standardChecks, { label: "Secret values in Firestore", value: "Prohibited", ready: true }], href: "/connections", linkLabel: "View connection design" },
  },
  demo: {
    eyebrow: "Safe scenario runner", title: "Demo Lab", icon: Boxes,
    description: "Run deterministic multilingual patient-journey, safety, provider-failure, STOP, campaign, and access-control scenarios without external effects.",
    actionLabel: "Run default scenario", actionHref: "/inbox",
    metrics: [
      { label: "Available scenarios", value: "14", detail: "Mapped to PRD acceptance journeys" },
      { label: "External effects", value: "0", detail: "All adapters are local simulators" },
      { label: "Languages", value: "3", detail: "Plus a mixed-language handoff" },
      { label: "Last suite", value: "Not run", detail: "Awaiting first local verification" },
    ],
    table: { title: "Scenario catalogue", description: "Each run resets to deterministic seed data", columns: ["Scenario", "Expected route", "Safety assertion", "State"], rows: [
      { primary: "Tamil appointment enquiry", secondary: "Appointments queue", third: "Mock slots only", status: "Ready", tone: "success" },
      { primary: "Sinhala laboratory enquiry", secondary: "Laboratory queue", third: "No report interpretation", status: "Ready", tone: "success" },
      { primary: "Mixed-language low confidence", secondary: "Human handoff", third: "AI does not guess", status: "Ready", tone: "success" },
      { primary: "Urgent-language message", secondary: "Urgent escalation", third: "Immediate safety copy", status: "Ready", tone: "success" },
      { primary: "50K campaign", secondary: "Governed simulation", third: "Zero external sends", status: "Ready", tone: "success" },
    ]},
    guardrail: { title: "Demo protection", description: "Persistent labels, generated references, disabled exports, locked production connections, and fail-closed provider adapters prevent accidental misuse.", checks: [...standardChecks, { label: "Hemas affiliation claim", value: "None", ready: true }, { label: "Synthetic reset", value: "Deterministic", ready: true }], href: "/compliance", linkLabel: "Review demo controls" },
  },
  help: {
    eyebrow: "Support", title: "Help & escalation", icon: HelpCircle,
    description: "Find demo runbooks, healthcare-safety escalation paths, connection diagnostics, and implementation documentation.",
    actionLabel: "Open Demo Lab", actionHref: "/demo-lab",
    metrics: [
      { label: "Runbooks drafted", value: "8", detail: "Implementation-stage material" },
      { label: "Open decisions", value: "12", detail: "Tracked in the approved PRD" },
      { label: "Production incidents", value: "0", detail: "No production system exists" },
      { label: "Support owner", value: "SafeNet", detail: "Demo implementation only" },
    ],
    table: { title: "Runbook library", description: "Links will be expanded as each implementation package is completed", columns: ["Runbook", "Audience", "Last review", "State"], rows: [
      { primary: "Synthetic demo operator guide", secondary: "Demo team", third: "Implementation phase", status: "Draft", tone: "warning" },
      { primary: "Urgent-language escalation", secondary: "Operations", third: "Implementation phase", status: "Draft", tone: "warning" },
      { primary: "Provider connection readiness", secondary: "Platform team", third: "Implementation phase", status: "Draft", tone: "warning" },
      { primary: "Production activation", secondary: "Hemas + SafeNet", third: "Not started", status: "Locked", tone: "neutral" },
    ]},
    guardrail: { title: "Emergency disclaimer", description: "This prototype is not an emergency service. Production copy and escalation paths require Hemas clinical governance approval.", checks: [...standardChecks, { label: "Emergency-service claim", value: "None", ready: true }], href: "/ai-knowledge", linkLabel: "Review safety behavior" },
  },
};
